/**
 * Copies the compiled ABIs the app needs into packages/core/src/perps/abi.ts
 * as `as const` literals, so viem types every call and decoded event. Run
 * after changing a contract: `npm run abi` (compiles first).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const artifact = (path) => JSON.parse(readFileSync(join(root, 'artifacts', 'contracts', path), 'utf8')).abi;

const abis = {
  AGRI_PERP_ABI: artifact('perps/AgriPerp.sol/AgriPerp.json'),
  AGRI_VAULT_ABI: artifact('perps/AgriVault.sol/AgriVault.json'),
  AGRI_FEED_ABI: artifact('oracles/AgriFeed.sol/AgriFeed.json'),
  // A Pyth feed as Chainlink-style rounds (the agri markets): the keeper pushes rounds and carries out rolls.
  PYTH_ROUND_FEED_ABI: artifact('oracles/PythRoundFeed.sol/PythRoundFeed.json'),
  // Prices the operator posts (the agri markets, read from Yahoo Finance): the keeper reports and rolls.
  REPORTED_ROUND_FEED_ABI: artifact('oracles/ReportedRoundFeed.sol/ReportedRoundFeed.json'),
  // A Uniswap V2 pool's TWAP as rounds (the RH Tokens markets): the keeper calls update() each minute.
  TWAP_ROUND_FEED_ABI: artifact('oracles/TwapRoundFeed.sol/TwapRoundFeed.json'),
  // Only what the app calls on the test collateral: minting for the testnet faucet.
  MOCK_USDC_ABI: artifact('test/MockUSDC.sol/MockUSDC.json').filter((x) => x.type === 'function' && x.name === 'mint'),
  // A Chainlink feed as its proxies expose it (AggregatorV3Interface) — the mock implements the same reads.
  CHAINLINK_FEED_ABI: artifact('test/MockAggregator.sol/MockAggregator.json').filter(
    (x) => x.type === 'function' && ['decimals', 'description', 'latestRoundData', 'getRoundData'].includes(x.name),
  ),
  // Local chains only: the worker posts prices into the mock feeds as new rounds.
  MOCK_AGGREGATOR_ABI: artifact('test/MockAggregator.sol/MockAggregator.json').filter((x) => x.type === 'function' && x.name === 'updateAnswer'),
};

const body = Object.entries(abis)
  .map(([name, abi]) => `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;`)
  .join('\n\n');

const out = join(root, '..', 'packages', 'core', 'src', 'perps', 'abi.ts');
writeFileSync(
  out,
  `/* Generated by contracts/scripts/export-abi.mjs from the compiled contracts — don't edit by hand. */\n\n${body}\n`,
);
console.log(`wrote ${out}`);
