import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

// `next-env.d.ts` is generated by Next and rewritten on every build — don't lint it.
const config = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // eslint-config-next 16 ships the React Compiler rules, and this one flags
    // effects that set state deliberately: client-only values applied after
    // hydration (Date.now(), localStorage) so SSR and first paint match, and
    // menus/drawers reset on navigation. Rewriting them would change how the
    // UI behaves, so they stay as they are — the rule still checks new code.
    files: [
      'src/components/chat/useCompanionChat.ts',
      'src/components/home/HeroBackground.tsx',
      'src/components/live2d/Live2DStage.tsx',
      'src/components/market/LiveVideo.tsx',
      'src/components/marketing/LandingHeader.tsx',
      'src/components/shell/AppShell.tsx',
      'src/lib/usePoll.ts',
    ],
    rules: { 'react-hooks/set-state-in-effect': 'off' },
  },
  globalIgnores(['.next/**', '.next-e2e*/**', 'node_modules/**', 'public/**', 'next-env.d.ts']),
]);

export default config;
